"""HTML tearsheet generation combining metrics and plots."""

import base64
import logging
from pathlib import Path

from src.contracts import BacktestResult
from src.reporting import plots
from src.reporting.metrics import compute_metrics

logger = logging.getLogger(__name__)

HTML_TEMPLATE = """<!DOCTYPE html>
<html>
<head>
    <title>Backtest Tearsheet — {signal_name}</title>
    <style>
        body {{ font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif;
               max-width: 1200px; margin: 0 auto; padding: 20px; background: #f5f5f5; }}
        h1 {{ color: #333; border-bottom: 2px solid #4CAF50; padding-bottom: 10px; }}
        h2 {{ color: #555; margin-top: 30px; }}
        table {{ border-collapse: collapse; width: 100%; margin: 15px 0; background: white;
                 box-shadow: 0 1px 3px rgba(0,0,0,0.1); }}
        th, td {{ padding: 10px 15px; text-align: left; border-bottom: 1px solid #eee; }}
        th {{ background: #4CAF50; color: white; }}
        tr:hover {{ background: #f9f9f9; }}
        .chart {{ margin: 20px 0; text-align: center; }}
        .chart img {{ max-width: 100%; border: 1px solid #ddd; border-radius: 4px; }}
        .grid {{ display: grid; grid-template-columns: 1fr 1fr; gap: 15px; }}
        .metric-card {{ background: white; padding: 15px; border-radius: 4px;
                        box-shadow: 0 1px 3px rgba(0,0,0,0.1); }}
        .metric-value {{ font-size: 1.5em; font-weight: bold; color: #333; }}
        .metric-label {{ font-size: 0.85em; color: #777; }}
    </style>
</head>
<body>
    <h1>Backtest Tearsheet: {signal_name}</h1>

    <h2>Performance Summary</h2>
    <table>
        <tr><th>Metric</th><th>Value</th></tr>
        {metrics_rows}
    </table>

    <h2>Equity Curve</h2>
    <div class="chart">{equity_chart}</div>

    <h2>Drawdown</h2>
    <div class="chart">{drawdown_chart}</div>

    <h2>Monthly Returns</h2>
    <div class="chart">{monthly_chart}</div>

    <h2>Rolling Sharpe Ratio</h2>
    <div class="chart">{sharpe_chart}</div>

    <h2>Position Concentration</h2>
    <div class="chart">{positions_chart}</div>

    <footer style="margin-top: 40px; color: #999; font-size: 0.8em;">
        Generated by Crypto Momentum Backtester
    </footer>
</body>
</html>"""


def generate_tearsheet(
    result: BacktestResult,
    output_dir: str | Path,
    benchmark_curve=None,
) -> Path:
    """Generate a complete HTML tearsheet from backtest results.

    Args:
        result: BacktestResult from the engine.
        output_dir: Directory to save the tearsheet and charts.
        benchmark_curve: Optional benchmark equity curve DataFrame.

    Returns:
        Path to the generated HTML file.
    """
    output_dir = Path(output_dir)
    output_dir.mkdir(parents=True, exist_ok=True)

    # Compute metrics
    metrics = compute_metrics(result.equity_curve, result.trade_log)

    # Generate charts
    equity_path = plots.plot_equity_curve(
        result.equity_curve, benchmark_curve, output_dir / "equity_curve.png"
    )
    drawdown_path = plots.plot_drawdown(
        result.equity_curve, output_dir / "drawdown.png"
    )
    monthly_path = plots.plot_monthly_returns_heatmap(
        result.equity_curve, output_dir / "monthly_returns.png"
    )
    sharpe_path = plots.plot_rolling_sharpe(
        result.equity_curve, output_path=output_dir / "rolling_sharpe.png"
    )
    positions_path = plots.plot_position_concentration(
        result.positions_over_time, output_dir / "position_concentration.png"
    )

    # Build HTML
    metrics_rows = "\n".join(
        f"        <tr><td>{k}</td><td>{v}</td></tr>"
        for k, v in metrics.to_dict().items()
    )

    html = HTML_TEMPLATE.format(
        signal_name=result.signal_name,
        metrics_rows=metrics_rows,
        equity_chart=_embed_image(equity_path),
        drawdown_chart=_embed_image(drawdown_path),
        monthly_chart=_embed_image(monthly_path),
        sharpe_chart=_embed_image(sharpe_path),
        positions_chart=_embed_image(positions_path),
    )

    html_path = output_dir / f"tearsheet_{result.signal_name}.html"
    html_path.write_text(html)
    logger.info(f"Generated tearsheet at {html_path}")

    # Also save metrics as JSON
    import json
    metrics_path = output_dir / f"metrics_{result.signal_name}.json"
    metrics_path.write_text(json.dumps(metrics.to_dict(), indent=2))

    # Save trade log as CSV
    if len(result.trade_log) > 0:
        csv_path = output_dir / f"trades_{result.signal_name}.csv"
        result.trade_log.to_csv(csv_path, index=False)

    return html_path


def _embed_image(path: Path) -> str:
    """Embed a PNG image as base64 in an HTML img tag."""
    if not path.exists():
        return "<p>Chart not available</p>"
    data = path.read_bytes()
    b64 = base64.b64encode(data).decode()
    return f'<img src="data:image/png;base64,{b64}" alt="chart">'
